/**
 * Marketing content for each business-type solution page.
 * Each entry powers a dedicated ultra-premium page at /solutions/:slug.
 */

export const SOLUTIONS = [
  {
    slug: 'trading',
    icon: 'Building2',
    accent: 'from-blue-500 to-indigo-600',
    glow: 'bg-blue-500/20',
    demoEmail: 'admin@maqder.com',
    image: '/images/solutions/trading.png',
    nameEn: 'Trading & Distribution',
    nameAr: 'التجارة والتوزيع',
    taglineEn: 'Inventory, purchasing and ZATCA invoicing — built for wholesalers & retailers.',
    taglineAr: 'المخزون والمشتريات والفوترة الإلكترونية — لتجار الجملة والتجزئة.',
    heroEn: 'Run your entire trading operation — from purchase order to ZATCA-compliant invoice — on one platform.',
    heroAr: 'أدر تجارتك بالكامل من أمر الشراء إلى الفاتورة المتوافقة مع هيئة الزكاة في منصة واحدة.',
    features: [
      { icon: 'Package', titleEn: 'Smart Inventory', titleAr: 'مخزون ذكي', descEn: 'SKU, barcode, multi-warehouse stock and low-stock alerts.', descAr: 'SKU والباركود ومخزون متعدد المستودعات وتنبيهات النفاد.' },
      { icon: 'Truck', titleEn: 'Purchasing & Suppliers', titleAr: 'المشتريات والموردون', descEn: 'Purchase orders, supplier ledgers, receiving and landed cost.', descAr: 'طلبات الشراء ودفاتر الموردين والاستلام والتكلفة.' },
      { icon: 'FileText', titleEn: 'ZATCA E-Invoicing', titleAr: 'الفوترة الإلكترونية', descEn: 'B2B/B2C invoices with XML signing, QR and live submission.', descAr: 'فواتير B2B/B2C مع توقيع XML ورمز QR وإرسال فوري.' },
      { icon: 'BarChart3', titleEn: 'Profit Analytics', titleAr: 'تحليلات الأرباح', descEn: 'Margins, best-sellers and real-time revenue dashboards.', descAr: 'الهوامش والأكثر مبيعاً ولوحات الإيرادات المباشرة.' },
    ],
    workflow: [
      { titleEn: 'Receive stock', titleAr: 'استلام المخزون', descEn: 'Create purchase orders and receive into warehouses.', descAr: 'أنشئ طلبات الشراء واستلمها في المستودعات.' },
      { titleEn: 'Sell & invoice', titleAr: 'البيع والفوترة', descEn: 'Issue ZATCA invoices that auto-deduct inventory.', descAr: 'أصدر فواتير ZATCA التي تخصم المخزون تلقائياً.' },
      { titleEn: 'Track & grow', titleAr: 'التتبع والنمو', descEn: 'Monitor margins and reorder before you run out.', descAr: 'راقب الهوامش وأعد الطلب قبل النفاد.' },
    ],
  },
  {
    slug: 'restaurant',
    icon: 'UtensilsCrossed',
    accent: 'from-amber-500 to-orange-600',
    glow: 'bg-amber-500/20',
    demoEmail: 'restaurant@maqder.com',
    image: '/images/solutions/restaurant.png',
    nameEn: 'Restaurant POS',
    nameAr: 'نقاط بيع المطاعم',
    taglineEn: 'Tables, kitchen display, card payments and ZATCA receipts — all in one POS.',
    taglineAr: 'الطاولات وشاشة المطبخ ومدفوعات البطاقات وإيصالات ZATCA في نظام واحد.',
    heroEn: 'A blazing-fast restaurant POS with kitchen routing, table management and integrated card terminals.',
    heroAr: 'نظام نقاط بيع سريع للمطاعم مع توجيه المطبخ وإدارة الطاولات وأجهزة بطاقات مدمجة.',
    features: [
      { icon: 'UtensilsCrossed', titleEn: 'Dine-in & Takeaway', titleAr: 'صالة وسفري', descEn: 'Table maps, order types and split checks.', descAr: 'خرائط الطاولات وأنواع الطلبات وتقسيم الفواتير.' },
      { icon: 'Coffee', titleEn: 'Kitchen Display', titleAr: 'شاشة المطبخ', descEn: 'Live kitchen tickets with prep statuses.', descAr: 'تذاكر مطبخ مباشرة مع حالات التحضير.' },
      { icon: 'CreditCard', titleEn: 'Card Terminal', titleAr: 'جهاز البطاقة', descEn: 'Process card payments on your POS machine and auto-complete orders.', descAr: 'عالج مدفوعات البطاقات على جهازك وأكمل الطلبات تلقائياً.' },
      { icon: 'Receipt', titleEn: 'ZATCA Receipts', titleAr: 'إيصالات ZATCA', descEn: 'Thermal receipts with compliant QR codes.', descAr: 'إيصالات حرارية مع رموز QR متوافقة.' },
    ],
    workflow: [
      { titleEn: 'Take the order', titleAr: 'استلام الطلب', descEn: 'Tap items, pick a table or takeaway.', descAr: 'اختر الأصناف والطاولة أو السفري.' },
      { titleEn: 'Fire to kitchen', titleAr: 'إرسال للمطبخ', descEn: 'Order appears instantly on the kitchen display.', descAr: 'يظهر الطلب فوراً على شاشة المطبخ.' },
      { titleEn: 'Pay by card', titleAr: 'الدفع بالبطاقة', descEn: 'Card terminal approves and the order closes automatically.', descAr: 'يوافق جهاز البطاقة ويُغلق الطلب تلقائياً.' },
    ],
  },
  {
    slug: 'laundry',
    icon: 'Sparkles',
    accent: 'from-emerald-500 to-teal-600',
    glow: 'bg-emerald-500/20',
    demoEmail: 'laundry@maqder.com',
    image: '/images/solutions/laundry.png',
    nameEn: 'Laundry Management',
    nameAr: 'إدارة المغاسل',
    taglineEn: 'Garment tracking, touch POS, weight billing and pickup scheduling.',
    taglineAr: 'تتبع الملابس ونقاط بيع باللمس والفوترة بالوزن وجدولة الاستلام.',
    heroEn: 'From drop-off to delivery — tag garments, bill by piece or weight, and take card payments.',
    heroAr: 'من الاستلام إلى التسليم — وسم الملابس والفوترة بالقطعة أو الوزن واستلام مدفوعات البطاقات.',
    features: [
      { icon: 'Sparkles', titleEn: 'Garment Tagging', titleAr: 'وسم الملابس', descEn: 'Auto-generated barcode tags per item.', descAr: 'وسوم باركود تلقائية لكل قطعة.' },
      { icon: 'Zap', titleEn: 'Express & Urgent', titleAr: 'خدمة عاجلة', descEn: 'Urgent fees and promised delivery dates.', descAr: 'رسوم عاجلة وتواريخ تسليم مؤكدة.' },
      { icon: 'CreditCard', titleEn: 'Card Payments', titleAr: 'مدفوعات البطاقة', descEn: 'Take card payments on your POS terminal.', descAr: 'استلم مدفوعات البطاقة على جهازك.' },
      { icon: 'ClipboardList', titleEn: 'Order Kanban', titleAr: 'لوحة الطلبات', descEn: 'Track every order from received to delivered.', descAr: 'تتبع كل طلب من الاستلام إلى التسليم.' },
    ],
    workflow: [
      { titleEn: 'Receive garments', titleAr: 'استلام الملابس', descEn: 'Tag items and pick services or treatments.', descAr: 'وسم القطع واختيار الخدمات.' },
      { titleEn: 'Process & track', titleAr: 'المعالجة والتتبع', descEn: 'Move orders across the kanban board.', descAr: 'حرّك الطلبات على لوحة الكانبان.' },
      { titleEn: 'Collect payment', titleAr: 'تحصيل الدفع', descEn: 'Cash or card on pickup, with ZATCA receipt.', descAr: 'نقداً أو بطاقة عند الاستلام مع إيصال ZATCA.' },
    ],
  },
  {
    slug: 'saloon',
    icon: 'Scissors',
    accent: 'from-fuchsia-500 to-purple-600',
    glow: 'bg-fuchsia-500/20',
    demoEmail: 'saloon@maqder.com',
    image: '/images/solutions/saloon.png',
    nameEn: 'Saloon & Barber',
    nameAr: 'صالون وحلاقة',
    taglineEn: 'Service POS, staff assignment, queue tickets and card payments.',
    taglineAr: 'نقاط بيع الخدمات وتعيين الموظفين وتذاكر الانتظار ومدفوعات البطاقات.',
    heroEn: 'Manage chairs, services and stylists with a fast POS and integrated card terminal.',
    heroAr: 'أدر الكراسي والخدمات والحلاقين بنظام نقاط بيع سريع وجهاز بطاقة مدمج.',
    features: [
      { icon: 'Scissors', titleEn: 'Service Catalog', titleAr: 'قائمة الخدمات', descEn: 'Price every service with tax and duration.', descAr: 'سعّر كل خدمة مع الضريبة والمدة.' },
      { icon: 'Users', titleEn: 'Staff Assignment', titleAr: 'تعيين الموظفين', descEn: 'Assign stylists and track their tickets.', descAr: 'عيّن الحلاقين وتتبع تذاكرهم.' },
      { icon: 'CreditCard', titleEn: 'Card Terminal', titleAr: 'جهاز البطاقة', descEn: 'Approve card payments and close the ticket.', descAr: 'وافق على مدفوعات البطاقة وأغلق التذكرة.' },
      { icon: 'CheckCircle2', titleEn: 'Queue Tickets', titleAr: 'تذاكر الانتظار', descEn: 'Walk-in queue management made simple.', descAr: 'إدارة طابور العملاء بسهولة.' },
    ],
    workflow: [
      { titleEn: 'Add services', titleAr: 'إضافة الخدمات', descEn: 'Build the ticket and assign a stylist.', descAr: 'كوّن التذكرة وعيّن الحلاق.' },
      { titleEn: 'Serve the client', titleAr: 'خدمة العميل', descEn: 'Track progress from waiting to completed.', descAr: 'تتبع الحالة من الانتظار إلى الإنجاز.' },
      { titleEn: 'Take payment', titleAr: 'استلام الدفع', descEn: 'Cash or card terminal, with ZATCA receipt.', descAr: 'نقداً أو بطاقة مع إيصال ZATCA.' },
    ],
  },
  {
    slug: 'travel_agency',
    icon: 'Globe',
    accent: 'from-sky-500 to-cyan-600',
    glow: 'bg-sky-500/20',
    demoEmail: 'travel@maqder.com',
    image: '/images/solutions/travel.png',
    nameEn: 'Travel Agency',
    nameAr: 'وكالة سفر',
    taglineEn: 'Margin-scheme VAT, ticket bookings and traveler invoicing.',
    taglineAr: 'ضريبة نظام الهامش وحجوزات التذاكر وفواتير المسافرين.',
    heroEn: 'Purpose-built for travel agencies — handle margin-scheme VAT and flight booking records with ease.',
    heroAr: 'مصمم لوكالات السفر — تعامل مع ضريبة الهامش وسجلات حجز الرحلات بسهولة.',
    features: [
      { icon: 'Globe', titleEn: 'Booking Records', titleAr: 'سجلات الحجز', descEn: 'PNR, ticket numbers, routes and passengers.', descAr: 'PNR وأرقام التذاكر والمسارات والركاب.' },
      { icon: 'Calculator', titleEn: 'Margin VAT', titleAr: 'ضريبة الهامش', descEn: 'Automatic margin-scheme tax calculation.', descAr: 'حساب ضريبة نظام الهامش تلقائياً.' },
      { icon: 'FileText', titleEn: 'Traveler Invoices', titleAr: 'فواتير المسافرين', descEn: 'ZATCA invoices linked to bookings.', descAr: 'فواتير ZATCA مرتبطة بالحجوزات.' },
      { icon: 'BarChart3', titleEn: 'Sales Reports', titleAr: 'تقارير المبيعات', descEn: 'Revenue and commission analytics.', descAr: 'تحليلات الإيرادات والعمولات.' },
    ],
    workflow: [
      { titleEn: 'Log the booking', titleAr: 'تسجيل الحجز', descEn: 'Capture PNR, route and passenger details.', descAr: 'سجّل PNR والمسار وبيانات الركاب.' },
      { titleEn: 'Invoice the margin', titleAr: 'فوترة الهامش', descEn: 'VAT is calculated on the margin automatically.', descAr: 'تُحسب الضريبة على الهامش تلقائياً.' },
      { titleEn: 'Submit to ZATCA', titleAr: 'الإرسال لـ ZATCA', descEn: 'Compliant invoices submitted in real time.', descAr: 'فواتير متوافقة تُرسل فورياً.' },
    ],
  },
  {
    slug: 'car_rental',
    icon: 'Truck',
    accent: 'from-rose-500 to-red-600',
    glow: 'bg-rose-500/20',
    demoEmail: 'rental@maqder.com',
    image: '/images/solutions/car-rental.png',
    nameEn: 'Car Rental',
    nameAr: 'تأجير السيارات',
    taglineEn: 'Fleet tracking, rental contracts, check-in/out POS and invoicing.',
    taglineAr: 'تتبع الأسطول وعقود التأجير ونقاط البيع للاستلام والتسليم والفوترة.',
    heroEn: 'Manage your fleet, KYC customers and rental contracts with check-in/out POS and ZATCA invoicing.',
    heroAr: 'أدر أسطولك وعملاءك وعقود التأجير مع نقاط بيع للاستلام والتسليم وفوترة ZATCA.',
    features: [
      { icon: 'Truck', titleEn: 'Fleet Management', titleAr: 'إدارة الأسطول', descEn: 'Vehicle availability, status and maintenance.', descAr: 'توفر المركبات وحالتها وصيانتها.' },
      { icon: 'ClipboardList', titleEn: 'Rental Contracts', titleAr: 'عقود التأجير', descEn: 'Digital contracts with terms and pricing.', descAr: 'عقود رقمية مع الشروط والتسعير.' },
      { icon: 'Users', titleEn: 'Customer KYC', titleAr: 'تحقق العملاء', descEn: 'ID/Iqama capture and customer registry.', descAr: 'حفظ الهوية/الإقامة وسجل العملاء.' },
      { icon: 'FileText', titleEn: 'Check-in / out', titleAr: 'الاستلام/التسليم', descEn: 'POS flows for handover and return.', descAr: 'نقاط بيع للتسليم والإرجاع.' },
    ],
    workflow: [
      { titleEn: 'Reserve a car', titleAr: 'حجز سيارة', descEn: 'Pick an available vehicle and customer.', descAr: 'اختر مركبة متاحة وعميلاً.' },
      { titleEn: 'Check out', titleAr: 'التسليم', descEn: 'Sign the contract and hand over keys.', descAr: 'وقّع العقد وسلّم المفاتيح.' },
      { titleEn: 'Return & invoice', titleAr: 'الإرجاع والفوترة', descEn: 'Check in the car and issue a ZATCA invoice.', descAr: 'استلم السيارة وأصدر فاتورة ZATCA.' },
    ],
  },
  {
    slug: 'construction',
    icon: 'Landmark',
    accent: 'from-slate-500 to-gray-700',
    glow: 'bg-slate-500/20',
    demoEmail: 'admin@maqder.com',
    image: '/images/solutions/construction.png',
    nameEn: 'Construction & Contracting',
    nameAr: 'المقاولات',
    taglineEn: 'Project billing, job costing and progress invoicing.',
    taglineAr: 'فوترة المشاريع وتكاليف الأعمال وفواتير الإنجاز.',
    heroEn: 'Track projects, cost every job and bill clients with ZATCA-compliant progress invoices.',
    heroAr: 'تتبع المشاريع واحسب تكلفة كل عمل وافوتر العملاء بفواتير إنجاز متوافقة مع ZATCA.',
    features: [
      { icon: 'ClipboardList', titleEn: 'Projects & Tasks', titleAr: 'المشاريع والمهام', descEn: 'Plan projects, phases and task workflows.', descAr: 'خطط المشاريع والمراحل وسير المهام.' },
      { icon: 'Calculator', titleEn: 'Job Costing', titleAr: 'تكاليف الأعمال', descEn: 'Track labor, materials and margins per job.', descAr: 'تتبع العمالة والمواد والهوامش لكل عمل.' },
      { icon: 'FileText', titleEn: 'Progress Invoices', titleAr: 'فواتير الإنجاز', descEn: 'Milestone-based ZATCA invoicing.', descAr: 'فوترة ZATCA حسب المراحل.' },
      { icon: 'BarChart3', titleEn: 'Profitability', titleAr: 'الربحية', descEn: 'Real-time project P&L visibility.', descAr: 'رؤية مباشرة لأرباح المشاريع.' },
    ],
    workflow: [
      { titleEn: 'Plan the project', titleAr: 'تخطيط المشروع', descEn: 'Set phases, tasks and budgets.', descAr: 'حدد المراحل والمهام والميزانيات.' },
      { titleEn: 'Cost the work', titleAr: 'تكلفة العمل', descEn: 'Capture labor and material costs.', descAr: 'سجّل تكاليف العمالة والمواد.' },
      { titleEn: 'Bill by milestone', titleAr: 'الفوترة بالمراحل', descEn: 'Issue progress invoices to ZATCA.', descAr: 'أصدر فواتير الإنجاز لـ ZATCA.' },
    ],
  },
]

export const getSolution = (slug) => SOLUTIONS.find((s) => s.slug === slug) || null
